FROM node:20
WORKDIR /app

COPY package.json ./
COPY .npmrc ./
COPY .env.* ./

RUN mkdir source
COPY tsconfig.json ./source
COPY package.json ./source

COPY src ./source/src
COPY ./.npmrc ./source

RUN cd source && npm run install:dep:dev && npm run build && cp -r ./build/src ../src
COPY credentials.json ./
COPY permissions.json ./

RUN rm -rf source
RUN npm run install:dep:prod

EXPOSE 5050
CMD ["npm", "run", "start:production"]